[build]
publish = "docs/public"
command = """hugo --gc \
  --source docs \
  --config docs/config.toml \
  --themesDir themes \
  --theme hugo-geekdoc """

[build.environment]
HUGO_VERSION = "0.60.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
