[build]
publish = "docs/public"
command = """hugo \
  --source docs \
  --config docs/config.toml \
  --themesDir docs/themes/hugo-geekdoc \
  --theme hugo-geekdoc """

[build.environment]
HUGO_VERSION = "0.51"
