baseURL = "https://rawrrdocs.netlify.app" 
title = "Rawrr Documentation"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
geekdocMenuBundle = true
enableGitInfo = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[param]
  geekdocLogo = "logo_rawrr_v_yellow.png"
    geekdocToC= 3

  geekdocRepo= https://github.com/thegeeklab/hugo-geekdoc
  geekdocEditPath= edit/main/exampleSite/content

  geekdocSearch= true
  geekdocSearchShowParent= true

  geekdocLegalNotice= https://thegeeklab.de/legal-notice/#contact-information
  geekdocPrivacyPolicy= https://thegeeklab.de/legal-notice/#privacy-policy

  geekdocImageLazyLoading= true
  geekdocDarkModeDim= true